services:
  laravel-workers-php:
    build: ./docker/php
    container_name: laravel-workers-php
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

  laravel-workers-nginx:
    image: nginx:latest
    container_name: laravel-workers-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - laravel-workers-php
    networks:
      - app-network


  laravel-workers-db:
    image: mysql:8.0
    container_name: laravel-workers-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  laravel-workers-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-workers-phpmyadmin
    restart: always
    environment:
      PMA_HOST: laravel-workers-db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - laravel-workers-db
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge